# Generated by Django 6.0 on 2026-07-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
