# Generated by Django 6.0 on 2026-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_role_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_brand_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
