# Generated by Django 6.0 on 2026-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
