# Generated by Django 6.0 on 2026-07-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_vendor_vendordeliveryrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('min_order_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('min_order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='users.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
