# Generated by Django 6.0 on 2026-07-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
        ('users', '0011_user_requested_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketrule',
            options={'verbose_name': 'basket rule', 'verbose_name_plural': 'basket rules'},
        ),
        migrations.AlterField(
            model_name='basketrule',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='users.vendor'),
        ),
    ]
