# Generated by Django 6.0 on 2026-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand_product_rating_product_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews_count',
        ),
    ]
