# Generated by Django 6.0 on 2026-07-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
